### ISSUE TITLE
Test fails when running with singularity

### ISSUE THREAD

**Issue by el239** [nf-core/fetchngs#101]
### Description of the bug

Repost from closed issue: https://github.com/nf-core/rnaseq/issues/383
Can't finish test run, "destination is already in the mount point list"

### Command used and terminal output

```console
nextflow run nf-core/fetchngs -profile test,singularity --outdir test_outdir

Command error:
  WARNING: While bind mounting '/erdos/elavelle/vigna/work/b5/250dd7d8fea316c771737cb79d8f39:/erdos/elavelle/vigna/work/b5/250dd7d8fea316c771737cb79d8f39': destination is already in the mount point list
  [ERROR] The server couldn't fulfill the request.
  [ERROR] Status: 400 Bad Request. Both list of IDs and query_key are empty
```

### System information

Nextflow version 22.04.3
Singularity version 3.8.7-1.el8
Linux HPC

**Comment by drpatelh** [comment]
Sorry...out of our hands but we are looking into a fix. See [here](https://github.com/nf-core/fetchngs/issues/98#issuecomment-1172028156)

**Comment by drpatelh** [comment]
Fixed the SRA download functionality but had to remove the GEO support. See [release notes](https://github.com/nf-core/fetchngs/releases/tag/1.7)Fixed the SRA download functionality but had to remove the GEO support. See [release notes](https://github.com/nf-core/fetchngs/releases/tag/1.7)
