### ISSUE TITLE
Test fails with singularity profile

### ISSUE THREAD

**Issue by el239** [nf-core/fetchngs#106]
### Description of the bug

Can't complete test running version 1.7. Do I need to try 1.8dev?

### Command used and terminal output

```console
nextflow run nf-core/fetchngs -profile test,singularity --outdir test_outdir

Error executing process > 'NFCORE_FETCHNGS:SRA:SRA_IDS_TO_RUNINFO (SRR12848126)'

Caused by:
  Process `NFCORE_FETCHNGS:SRA:SRA_IDS_TO_RUNINFO (SRR12848126)` terminated with an error exi
t status (1)

Command executed:

  echo SRR12848126 > id.txt
  sra_ids_to_runinfo.py \
      id.txt \
      SRR12848126.runinfo.tsv \
  
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_FETCHNGS:SRA:SRA_IDS_TO_RUNINFO":
      python: $(python --version | sed 's/Python //g')
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  WARNING: While bind mounting '/erdos/elavelle/vigna/work/f7/81d73260a94454ca3e8486b3d42153:/erdos/elavelle/vigna/work/f7/81d73260a94454ca3e8486b3d42153': destination is already in the mount point list
  [ERROR] No matches found for database id SRR12848126!
  Line: 'SRR12848126'
```

### System information

Nextflow version 22.04.3
Singularity version 3.8.7-1.el8
Linux HPC

**Comment by sparktx-chao-di** [comment]
Same error with docker on ec2

**Comment by drpatelh** [comment]
Can you pull the latest code (`nextflow pull nf-core/fetchngs`) and run using the `-r dev` parameter please? There have been a few breaking changes in the NCBI API recently that have also broken this pipeline.

**Comment by el239** [comment]
The pull returns:
`Checking nf-core/fetchngs ...
 Already-up-to-date - revision: e4084fec46 [dev]`
But running with that option completes the test successfully!
`nextflow run nf-core/fetchngs -r dev -profile test,singularity --outdir test_outdir`
However, it's still hanging on curl with my dataset until connection is reset..
I've made sure the files are in SRR.

`Error executing process > 'NFCORE_FETCHNGS:SRA:SRA_FASTQ_FTP (SRX2885748_SRR5648383)'

Caused by:
  Process `NFCORE_FETCHNGS:SRA:SRA_FASTQ_FTP (SRX2885748_SRR5648383)` terminated with an error exit 
status (56)

Command executed:

  curl \
      --retry 5 --continue-at - --max-time 1200 \
      -L ftp.sra.ebi.ac.uk/vol1/fastq/SRR564/003/SRR5648383/SRR5648383_1.fastq.gz \
      -o SRX2885748_SRR5648383_1.fastq.gz
  
  echo "76082edb98d087ff4e1d80fec3fc719f  SRX2885748_SRR5648383_1.fastq.gz" > SRX2885748_SRR5648383_
1.fastq.gz.md5
  md5sum -c SRX2885748_SRR5648383_1.fastq.gz.md5
curl \
      --retry 5 --continue-at - --max-time 1200 \
      -L ftp.sra.ebi.ac.uk/vol1/fastq/SRR564/003/SRR5648383/SRR5648383_2.fastq.gz \
      -o SRX2885748_SRR5648383_2.fastq.gz
  
  echo "444b9b612d16ad3c7546bda7cc41b8ad  SRX2885748_SRR5648383_2.fastq.gz" > SRX2885748_SRR5648383_2.fastq.gz.md5
  md5sum -c SRX2885748_SRR5648383_2.fastq.gz.md5
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_FETCHNGS:SRA:SRA_FASTQ_FTP":
      curl: $(echo $(curl --version | head -n 1 | sed 's/^curl //; s/ .*$//'))
  END_VERSIONS

Command exit status:
  56

Command output:
  (empty)
Command error:
  WARNING: While bind mounting '/erdos/elavelle/vigna/work/11/6de42dcc1c6e356b5811a8d6981696:/erdos/elavelle/vigna/work/11/6de42dcc1c6e356b5811a8d6981696': destination is already in the mount point list
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
  
    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  curl: (56) Recv failure: Connection reset by peer

Work dir:
  /erdos/elavelle/vigna/work/11/6de42dcc1c6e356b5811a8d6981696

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
`

**Comment by el239** [comment]
It works with the --force_sratools_download option!

`nextflow run nf-core/fetchngs -r dev --input IDs.txt --outdir vignaDevSRRs -profile singularity --force_sratools_download --nf_core_pipeline rnaseq`
