### ISSUE TITLE
Downloading of controlled data

### ISSUE THREAD

**Issue by JiaGengChang** [nf-core/fetchngs#107]
### Description of feature

I would like to request for the ability to pass in our dbGAP credentials through the --ngc flag of SRAtools so as to be able to download controlled data.

**Comment by drpatelh** [comment]
Hi @JiaGengChang ! Can you send us an example command of how you would do this outside of the pipeline please and any other credentials settings you need to use.

**Comment by celinesin** [comment]
My command is:

prefetch $currSRA --ngc $path_key

where 
$currSRA is a SRA id
$path_key is a *.ngc file

**Comment by drpatelh** [comment]
Duplicate of https://github.com/nf-core/fetchngs/issues/138
