### ISSUE TITLE
Final samplesheet is not created when --skip_fastq_download is provided

### ISSUE THREAD

**Issue by SchwarzMarek** [nf-core/fetchngs#114]
### Description of the bug

The `--skip_fastq_download` flag implies that only the `fastq` files will not be downloaded. When using the  `--skip_fastq_download` and `--nf_core_pipeline rnaseq` together, the `fastq` files are not downloaded (expected), but sample sheet is not created (unexpected).

### Command used and terminal output

```console
nextflow run nf-core/fetchngs -profile docker --nf_core_pipeline rnaseq --outdir test --input temp.txt --max_cpus 2 --max_memory 5.GB --skip_fastq_download
```

### Relevant files

[temp.txt](https://github.com/nf-core/fetchngs/files/9646080/temp.txt)

### System information

N E X T F L O W  ~  version 22.04.5
Launching `https://github.com/nf-core/fetchngs` [nostalgic_meitner] DSL2 - revision: b79cde2fb5 [master]

**Comment by pinin4fjords** [comment]
+ 1 following, encountered this today
