### ISSUE TITLE
--force_sratools_download results in different fastq names compared to FTP download

### ISSUE THREAD

**Issue by ojziff** [nf-core/fetchngs#119]
### Description of the bug

Hey,

is it intended that  `--force_sratools_download` results in different fastq names? 

Without  `--force_sratools_download` the fastqs have naming format `SRX[0-9]+SRR[0-9][1-2].fastq.gz` whereas with `--force_sratools_download` the naming is `SRR[0-9]+_[1-2].fastq.gz`.

This means that you cannot combine downloading fastqs both with and without `--force_sratools_download` in the event of ebi curl errors (without) e.g. 

```
Command error:
  INFO:    Converting SIF file to temporary sandbox...
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
  
    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  curl: (7) Failed to connect to ftp.sra.ebi.ac.uk port 21 after 1614 ms: Connection refused
```
and fasterq-dump errors (with) e.g.
```
Command error:
  INFO:    Converting SIF file to temporary sandbox...
  .command.run: fork: Cannot allocate memory
  fasterq-dump was killed (signal 9 SIGKILL)
  .command.run: line 163: kill: (80666) - No such process
  INFO:    Cleaning up image...
```

Many thanks,
Oliver

**Comment by drpatelh** [comment]
Fixed in https://github.com/nf-core/fetchngs/pull/125
