### ISSUE TITLE
Sample sheet as Tower report

### ISSUE THREAD

**Issue by pinin4fjords** [nf-core/fetchngs#121]
### Description of feature

Apologies if I've missed the feature somewhere, but currently nothing appears in the Tower reports when running this workflow, which to my rookie eyes looks like it's due to the lack of a tower.yml.

Can the sample sheet be a Tower report (I'll see if I can make a PR for that)? Even better if it could also make a Tower dataset.

**Comment by pinin4fjords** [comment]
This also needs a resolution to https://github.com/nf-core/fetchngs/issues/111 / https://github.com/nf-core/fetchngs/issues/118 (I hacked our fork to CSV input for Tower, but I'll try to make a better solution to PR)

**Comment by drpatelh** [comment]
Added in https://github.com/nf-core/fetchngs/pull/123
