### ISSUE TITLE
WARN: Cannot read project manifest -- Cause: API rate limit exceeded 

### ISSUE THREAD

**Issue by StevenWingett** [nf-core/fetchngs#13]
## Description of the bug

Thank you for this is excellent tool.  It has worked fine for me in the past, but I've started getting the message below.

(I can't expect users on the system to have logged in to GitHub.)

Do you know how I can solve the problem?  Other nf-core pipelines currently work on my machine.

## Steps to reproduce

swingett@cell-bio-xeon:~/data1_wingett/Magda/classifier/HipSci_Full_Download$ nextflow run fetcher --input to_download_ERR.txt -bg
swingett@cell-bio-xeon:~/data1_wingett/Magda/classifier/HipSci_Full_Download$ N E X T F L O W  ~  version 21.04.1
Pulling nextflow-io/fetcher ...
WARN: Cannot read project manifest -- Cause: API rate limit exceeded -- Provide your GitHub user name and password to get a higher rate limit
API rate limit exceeded -- Provide your GitHub user name and password to get a higher rate limit

## System

- Hardware: 
- Executor: 
- OS: 
- Version 

## Nextflow Installation

- Version:

**Comment by StevenWingett** [comment]
## Check Documentation

I have checked the following places for your error:

- [ ] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [ ] [nf-core/fetchngs pipeline documentation](https://nf-co.re/fetchngs/usage)

## Description of the bug



## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: 
2. See error: 

## Expected behaviour



## Log files

Have you provided the following extra information/files:

- [ ] The command used to run the pipeline
- [ ] The `.nextflow.log` file 

## System

- Hardware: 
- Executor: 
- OS: 
- Version 

## Nextflow Installation

- Version: 

## Container engine

- Engine: 
- version: 

## Additional context

**Comment by StevenWingett** [comment]
## Description of the bug

(Just re-pasting my message)

Thank you for this is excellent tool.  It has worked fine for me in the past, but I've started getting the message below.

(I can't expect users on the system to have logged in to GitHub.)

Do you know how I can solve the problem?  Other nf-core pipelines currently work on my machine.


## Steps to reproduce

swingett@cell-bio-xeon:~/data1_wingett/Magda/classifier/HipSci_Full_Download$ nextflow run fetcher --input to_download_ERR.txt -bg
swingett@cell-bio-xeon:~/data1_wingett/Magda/classifier/HipSci_Full_Download$ N E X T F L O W  ~  version 21.04.1
Pulling nextflow-io/fetcher ...
WARN: Cannot read project manifest -- Cause: API rate limit exceeded -- Provide your GitHub user name and password to get a higher rate limit
API rate limit exceeded -- Provide your GitHub user name and password to get a higher rate limit


## System

- Hardware:Desktop
- Executor: local
- OS: Ubuntu
- Version Ubuntu 18.04.4 LTS 

## Nextflow Installation

- Version: version 21.04.1

**Comment by drpatelh** [comment]
Hi @StevenWingett ! Hope you are well! Long time no speak :)

It looks like you are trying to run a pipeline called `fetcher` from the messages above whereas this pipeline is called `fetchngs`?

```console
Pulling nextflow-io/fetcher ...
```

You shouldn't really be hitting any Github API limits with this pipeline as the only download from Github is the pipeline itself and this is only done once when you trigger the run and is cached locally thereafter in `~/.nextflow/assets/nf-core/fetchngs` anyway.

**Comment by StevenWingett** [comment]
Hi,

I am fine thank you and I hope you are well too.  Hopefully there will be bioinformatics meet-ups etc. once again before too long.

That is embarrassing :-(   That is the second time I have got the name of this pipeline incorrect.  Many thanks for your help and it all seems to be working now!  Thank you.

Actually, if I may make a suggestion, have you considered at some point adding functionality to rename the downloaded FASTQ files to include sample/species/experiment name, in a similar fashion to Phil's SRA Explorer.  Just a suggestion.

Many thanks once again.

All the best,

Steven

**Comment by drpatelh** [comment]
No worries! 🤞🏽 

Yes, we discussed the sample renaming on Slack a few days ago but I am not a big fan of the super-dooper-long names generated by SRAExplorer. Also, the info for this sort of renaming is quite inconsistent in the SRA 😏 As it goes, I have been working on outputting a `mappings.tsv` with just some of the pertinent information that can be used to rename the samples downstream or in MultiQC.

**Comment by drpatelh** [comment]
Hopefully, I will get another release out this week with that included.

**Comment by StevenWingett** [comment]
Fantastic!

 

It always surprises me how hard it is to download FASTQ files.

 

Thanks,

Steven

 

From: Harshil Patel ***@***.***>
Reply to: nf-core/fetchngs ***@***.***>
Date: Monday, 21 June 2021 at 15:51
To: nf-core/fetchngs ***@***.***>
Cc: Steven Wingett ***@***.***>, State change ***@***.***>
Subject: Re: [nf-core/fetchngs] WARN: Cannot read project manifest -- Cause: API rate limit exceeded (#13)

 

Hopefully, I will get another release out this week with that included.
