### ISSUE TITLE
download of big files time out and don't resume

### ISSUE THREAD

**Issue by suhrig** [nf-core/fetchngs#169]
### Description of the bug

The process `NFCORE_FETCHNGS:SRA:SRA_FASTQ_FTP` is configured to cancel a download if it takes longer than 1200 seconds (see [here](https://github.com/nf-core/fetchngs/blob/27067828746a19484d40d4d175f7e14044e5beb3/conf/modules.config#L57)). Long-running downloads are thus interrupted and the following error is raised:

```
curl: (28) Operation timed out after 1200000 milliseconds with 23601274614 out of 49920124494 bytes received
Warning: Problem : timeout. Will retry in 1 seconds. 5 retries left.
Throwing away 23601274614 bytes
```

Unfortunately, `curl` does not resume a download when it retries - even when the parameter`--continue-at -` is used. As stated in the error message, it "throws away" the downloaded data and starts over. This effectively means that the download never completes.

1. What's the point of the parameter `--max-time`? Is it to catch stalling downloads? Wouldn't it be better to detect stalling downloads as such, instead of assuming that any download that takes longer than 1200s must have stalled? Namely, `--speed-limit 1 --speed-time 60` instructs `curl` to assume a download has stalled if the speed was less than 1 byte/sec for 60 seconds in a row?
2. This does not resolve the main issue that downloads are not resumed upon retries. One has to wrap the `curl` command in a bash for-loop in conjunction with `--continue-at -`. Alternatively: Why not use `wget`, which does not throw away downloaded data upon retry and also has stall detection (`--read-timeout=60`)?

**Comment by Midnighter** [comment]
Those are all very good suggestion. Would you be up for making creating a PR that implements the most general ones?

**Comment by suhrig** [comment]
Yes, I can do that.

**Comment by drpatelh** [comment]
Great! Thank you 🙏🏽

**Comment by samleenz** [comment]
any update on this -  or thoughts on an alternative solution in the mean time? 

Downloading from the ENA ftp servers appears to be slow at our institute currently for some reason, so the curl command is failing on the runtime. 

Thanks!

**Comment by suhrig** [comment]
I already have implemented a patch. I'm testing it locally. But the tests take longer than usual due to ENA/SRA being slow at the moment. I will submit a pull request with the changes I have so far, then you can test it in parallel and benefit from the enhancements now already.

**Comment by suhrig** [comment]
Here is the PR: #229. Feel free to test and give feedback. Thanks.

**Comment by amizeranschi** [comment]
Currently running into similar trouble with failed FTP downloads that don't get to finish, even after a couple of retries.

@suhrig thanks for submitting your PR, but it doesn't look like it's been merged yet due to some conflicts. Could you have another look?

**Comment by suhrig** [comment]
A hope to get around doing this next week. Sorry for the delay.

**Comment by drpatelh** [comment]
x-ref #241 replacement for PR #229

**Comment by drpatelh** [comment]
Should be fixed in https://github.com/nf-core/fetchngs/pull/241
