### ISSUE TITLE
Support .ngc file for dbgap downloads

### ISSUE THREAD

**Issue by alexblaessle** [nf-core/fetchngs#233]
### Description of feature

So far the pipeline only support .jwt files for cloud download. It would be nice to also support .ngc files for non-cloud envs.

**Comment by alexblaessle** [comment]
Resolved in PR https://github.com/nf-core/modules/pull/4303.

**Comment by drpatelh** [comment]
Fixed in https://github.com/nf-core/fetchngs/pull/245/commits/20769af129780bb304db51f1d38543702ed2b44a
