### ISSUE TITLE
URGENT: pin nf-validation version

### ISSUE THREAD

**Issue by nvnieuwk** [nf-core/fetchngs#287]
### Description of the bug

To prevent breaking this pipeline in the near future, the nf-validation version should be pinned to version 1.1.3 like:

```
plugins {
    id 'nf-validation@1.1.3'
}
```

**Comment by drpatelh** [comment]
Fixed through template updates https://github.com/nf-core/fetchngs/commit/5462bdb81b6260db7ae0b61b82ee610d56dfa18a#diff-ce7465a8e67b3b9c95696db1146ca7e6328f075e08a3d64062b87aa8608fc4ea
