### ISSUE TITLE
Error when using sratools: This sra toolkit installation has not been configured

### ISSUE THREAD

**Issue by RoganGrant** [nf-core/fetchngs#76]
### Description of the bug

First of all, love this tool. Thank you for putting this together.

I'm running into an issue when using the `--force_sratools_download` command. It runs without issue until the prefetch step, at which point every task fails with the error listed below.
 
Do I need to configure this on my hpc, or is this an actual bug?

### Command used and terminal output

```console
nextflow run nf-core/fetchngs \
-r 1.5 \
--input '/projects/b1042/MisharinLab/rgrant/220226_Zhang_reanalysis/220226_Zhang_BMDM_SRR_Acc_List.txt' \
-profile nu_genomics \
--nf_core_pipeline rnaseq \
--force_sratools_download

> This sra toolkit installation has not been configured.
> Before continuing, please run: vdb-config --interactive
> For more information, see https://www.ncbi.nlm.nih.gov/sra/docs/sra-cloud/
> Failed attempt 1 of 5. Retrying in 1 s.
> This sra toolkit installation has not been configured.
> Before continuing, please run: vdb-config --interactive
> For more information, see https://www.ncbi.nlm.nih.gov/sra/docs/sra-cloud/
> Failed attempt 2 of 5. Retrying in 2 s.
> This sra toolkit installation has not been configured.
> Before continuing, please run: vdb-config --interactive
> For more information, see https://www.ncbi.nlm.nih.gov/sra/docs/sra-cloud/
> Failed attempt 3 of 5. Retrying in 4 s.
> This sra toolkit installation has not been configured.
> Before continuing, please run: vdb-config --interactive
> For more information, see https://www.ncbi.nlm.nih.gov/sra/docs/sra-cloud/
> Failed attempt 4 of 5. Retrying in 8 s.
> This sra toolkit installation has not been configured.
> Before continuing, please run: vdb-config --interactive
> For more information, see https://www.ncbi.nlm.nih.gov/sra/docs/sra-cloud/
> Failed after 5 attempts.
```

### Relevant files

[220226_Zhang_BMDM_SRR_Acc_List.txt](https://github.com/nf-core/fetchngs/files/8147302/220226_Zhang_BMDM_SRR_Acc_List.txt)

### System information

Nextflow: version 21.10.5 build 5658
Hardware: HPC
Executor: slurm
OS: Red Hat Enterprise Linux Server 7.5 (Maipo)
Container: singularity version 3.8.1
Fetchngs version: 1.5

**Comment by RoganGrant** [comment]
PS sorry for double issue; you can delete #75

**Comment by RoganGrant** [comment]
Realizing from Slack discussions that this is not a new issue. I would of course prefer to use the default, but either EBI is down yet again or my HPC blocks the connection. 

Loading the sratools module loads my usual config, but my settings do not seem to play well with the container. In the meantime I can of course just use sratools directly, but are there config settings that will work? It would be a good intermediate solution for now.

**Comment by Midnighter** [comment]
Hi @RoganGrant,

Apologies for the long silence. Do you have a configuration file available to you? If you have a working configuration, you could try the following. Say your file is in `"${HOME}/.ncbi/user-settings.mkfg"`.

Create a local configuration `local.config` which you then call with `nextflow -c local.config run ...`.

```groovy
process {
    withName: SRATOOLS_PREFETCH {
        containerOptions = '-v "${HOME}/.ncbi/user-settings.mkfg:/opt/user-settings.mkfg" -e NCBI_SETTINGS=/opt/user-settings.mkfg'
    }
    withName: SRATOOLS_FASTERQDUMP {
        containerOptions = '-v "${HOME}/.ncbi/user-settings.mkfg:/opt/user-settings.mkfg" -e NCBI_SETTINGS=/opt/user-settings.mkfg'
    }
}
```

**Comment by RoganGrant** [comment]
Thank you; I will try this!
