### ISSUE TITLE
SRA_IDS_TO_RUNINFO fails due to bad request

### ISSUE THREAD

**Issue by dmalzl** [nf-core/fetchngs#99]
### Description of the bug

I think this is related to issue [#98](https://github.com/nf-core/fetchngs/issues/98) where the storage mode of files changed in the SRA. Several DRR and SRR accessions fail to be retrieved. Since this information is still in the ENA FTP I fixed it buy just bypassing the SRA efetch request and directly use the ENA FTP for this. I think it would be reasonable to try the SRA (since most of my accessions worked) and fall back to the ENA FTP if the SRA efetch request fails instead of exiting the process

### Command used and terminal output

```console
nextflow run nf-core/fetchngs ... --force_sratools_download

Error printed for some SRR and DRR accessions:

[ERROR] The server couldn't fulfill the request.
[ERROR] Status: 400 Bad Request. Both list of IDs and query_key are empty
```

**Comment by drpatelh** [comment]
Sorry...out of our hands but we are looking into a fix. See [here](https://github.com/nf-core/fetchngs/issues/98#issuecomment-1172028156)

**Comment by drpatelh** [comment]
Fixed the SRA download functionality but had to remove the GEO support. See [release notes](https://github.com/nf-core/fetchngs/releases/tag/1.7)
